name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    build:
        name: "test"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name:
              run: |
                echo ${{ secrets.test }}
            - name: Setup upterm session
              uses: lhotari/action-upterm@v1