name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    build:
      name: "test"
      runs-on: ubuntu-latest
      outputs:
        test: ${{ steps.secret.outputs.test }}
      steps:
        - uses: actions/checkout@v2
        - name: secret
          run: |
            echo "::set-output name=mysecret::${{ secrets.test }}"
        - name: Setup upterm session
          uses: lhotari/action-upterm@v1
    test:
      name: "check secret"
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: read job 1 secret
          run: |
            echo ${{needs.build.outputs.test}} 